insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('028014', '思想道德修养与法律基础', '3', '3', '0', '48', '0', 'Ideological,Moral Cultivation and Law Basics');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('028011', '马克思主义基本原理', '3', '3', '0', '48', '0', 'Basic principles of  Marxism');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('049001', '幸福心理学', '2', '2', '0', '32', '0', 'Psychology of Happiness');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('028013', '中国近现代史纲要', '2', '2', '0', '32', '0', 'Conspectus of Chinese Modern History');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('024011', '创业基础', '2', '2', '0', '32', '0', '创业基础');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('037001', '军事理论', '2', '2', '0', '32', '0', 'Military Theory');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('028015', '毛泽东思想和中国特色社会主义理论体系概论', '6', '4', '2', '64', '32', 'an introduction to mao zedong thought and the theory system');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267244', 'C语言程序设计（软件2013）', '6', '4', '4', '64', '64', 'C Programming Language(Software)');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267164', '数字逻辑基础', '4', '4', '0', '64', '0', 'Fundamentals of Digital Logic');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('024009', '新生名师导航', '2', '2', '0', '32', '0', '新生名师导航');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267214', '线性代数及应用（4分）', '4', '3', '1', '48', '16', 'Linear Algebra and Its Applications');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267165', '离散数学及应用Ⅰ', '4', '4', '0', '64', '0', 'Discrete Mathematics and Its Applications Ⅰ');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267093', '软件工程导论（软件）', '3', '2', '2', '32', '32', 'Introduction of Software Engineering');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267058', '计算机网络与通信技术', '4', '3', '2', '48', '32', 'Computer Network & communications technology');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267213', '需求工程', '3', '2', '2', '32', '32', 'Requirements Engineering');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267095', '软件项目管理（3分）', '3', '2', '2', '32', '32', 'Software Project Management');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267211', '质量保证与测试（3分）', '3', '2', '2', '32', '32', 'Quality Assurance and Testing');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('024005', '毕业实习（5分）', '5', '0', '10', '', '160', '毕业实习（5分）');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('024001', '毕业设计（论文）', '5', '0', '10', '', '160', '毕业设计（论文）');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267092', 'web程序设计（软件）', '3', '2', '2', '32', '32', 'Web Programming');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267271', '计算机英语（2分）', '2', '2', '0', '32', '0', 'Computer English');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267217', 'Linux基础', '3', '2', '2', '32', '32', 'Linux System Foundation');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267166', '离散数学及应用Ⅱ', '3', '3', '0', '48', '0', 'Discrete Mathematics Anderson Its ApplicationsⅠⅠ');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267104', '大型数据库技术', '5', '4', '2', '64', '32', 'Database technology application');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267219', '计算机组成原理（2013）', '4', '4', '0', '64', '0', 'Principles of Computer Organization');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267255', '前端开发实践', '3', '2', '2', '32', '32', 'The front-end development practices');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267044', 'JSP程序设计', '3', '2', '2', '32', '32', 'JSP Programming');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267105', '大型软件设计与体系结构', '5', '4', '2', '64', '32', 'Large-scale software design and architecture');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267089', '算法设计与分析（2分）', '2', '2', '0', '32', '0', 'The Design and Analysis of Algorithms');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('262121', '网络程序设计（4分）', '4', '3', '2', '48', '32', '网络程序设计（4分）');
insert into course(number, cname, score, chour, lhour, tchour, tlhour, ename) values('267102', 'XML程序设计（3分）', '3', '2', '2', '32', '32', 'XML Programming');
